name: mediconnect
description: MediConnect Mobile App
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # State Management
  provider: ^6.1.2
  path_provider: ^2.1.5
  
  # Network & API
  http: ^1.3.0
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  path: ^1.9.1
  http_parser: ^4.1.2

  # Storage
  shared_preferences: ^2.5.2
  image_picker: ^1.1.2
  mime: ^2.0.0
  permission_handler: ^11.4.0
  device_info_plus: ^11.3.3
  
  # UI Components
  flutter_svg: ^2.0.17
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  loading_animation_widget: ^1.3.0
  
  # Utils
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.2.2 
  timeago: ^3.2.2 
  
  # Form Validation
  form_validator: ^2.1.1
  
  # Navigation
  go_router: ^14.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/images/
  #   - assets/icons/